### ISSUE TITLE
Flow settings - expand with minimum cell spacing, ads the spacing to last cell on the right

### ISSUE THREAD

**Issue by gbucur** [ptc-iot-sharing/BMCoreUI#1]
Tested on TWX 8.5
On browser resize, it goes to behaving as it should.

**Comment by BogdanMihaiciuc** [comment]
Fixed with fc5793a.

The issue was that iScroll was initialised after the initial layout pass which caused the initial scrollbar measurement to assume that the standard scrollbar was used. This would lead to an incorrect initial layout which would be solved in subsequent passed which correctly saw that iScroll was used.
